project:
  type: website
  output-dir: docs

website:
  google-analytics: G-FJF9QG31QF
  title: "Colors of Music"
  navbar:
    left:
      - href: ca.html
        text: Correspondence Analysis Factor Map
      - href: about.qmd
        text: About us
      - icon: github
        href: https://github.com/vguillemot/colorofmusic

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

