---
title: "Correspondence analysis"
subtitle: "Colors of music"
output: html_document
---

```{r setup, include=FALSE}
## Dans ce chunk :
# mettez vos options de chunk par défaut...  
knitr::opts_chunk$set(echo = FALSE)
# ... chargez toutes vos librairies
library(factoextra)
library(FactoMineR)
library(ggiraph)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(pander)
library(pheatmap)
library(PMA)
library(Polychrome)
library(reshape2)
# R functions
```

#  {.tabset}

```{r data}
data("colorOfMusic", package = "data4PCCAR")
tab <- colorOfMusic$contingencyTable
```


```{r interactive}
res.ca <- CA(tab, graph = FALSE)

dat.row <- data.frame(
  res.ca$row$coord,
  colorOfMusic$colorInformation)

dat.col <- data.frame(
  res.ca$col$coord, 
  musics = rownames(res.ca$col$coord))

dat.col$onclick <- sprintf('var audio= new Audio("https://github.com/vguillemot/colorofmusic/raw/main/music/%s.mp3"); audio.play();', c("videogame", "jazz", "country", "rap", "pop", "opera", "lowF", "highF", "middleF"))


pc.int <- ggplot() +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_label(aes(Dim.1, Dim.2, color = I(colorCodes), label = colorNames),
             dat.row, size = 2, fontface = 2) +
  geom_point_interactive(aes(Dim.1, Dim.2, onclick = onclick), dat.col, shape = "♪", size = 4) +
  geom_text_repel(aes(Dim.1, Dim.2, label = musics), dat.col, fontface = 3) +
  theme_bw() +
  labs(x = "Dim. 1 (38.6%)",
       y = "Dim. 2 (25.9%)",
       title = "CA factor map")


girobj <- girafe(
  ggobj = pc.int)

girobj

```
