---
title: "Correspondence analysis"
subtitle: "Colors of music"
output: html_document
---

```{r setup, include=FALSE}
## Dans ce chunk :
# mettez vos options de chunk par défaut...  
knitr::opts_chunk$set(echo = FALSE)
# ... chargez toutes vos librairies
library(factoextra)
library(FactoMineR)
library(ggiraph)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(pander)
library(pheatmap)
library(PMA)
library(Polychrome)
library(reshape2)
# R functions
```

# {.tabset}


```{r data}
data("colorOfMusic", package = "data4PCCAR")
tab <- colorOfMusic$contingencyTable
```

## Colors


```{r colors}
swatch(setNames(colorOfMusic$colorInformation$colorCodes, colorOfMusic$colorInformation$colorNames), main = "The 10 colors of the study")
```

## Table

```{r tab, results='asis'}
pander::pandoc.table(tab)
```

## Heatmap

```{r heatmap}
# Color annotation
annotrow <- data.frame(
  Colors = colorOfMusic$colorInformation$colorNames, 
  row.names = colorOfMusic$colorInformation$colorNames)
# Custom colors
annotcolors <- list(
  Colors = setNames(colorOfMusic$colorInformation$colorCodes,
                      colorOfMusic$colorInformation$colorNames))
# Distance du chi-2 pour les lignes et les colonnes
Drow <- as.dist(ExPosition::chi2Dist(tab)$D)
Dcol <- as.dist(ExPosition::chi2Dist(t(tab))$D)
# Carte de chaleur
pheatmap(tab,
         clustering_method = "ward.D2",
         clustering_distance_rows = Drow,
         clustering_distance_cols = Dcol,
         annotation_row = annotrow, 
         annotation_colors = annotcolors, 
         color = grDevices::grey.colors(12, start = 1, end = 0),
         border_color = NA)
```

## CA

```{r ca_graphs}
res.ca <- CA(tab, graph = FALSE)

dat.row <- data.frame(
  res.ca$row$coord,
  colorOfMusic$colorInformation)

dat.col <- data.frame(
  res.ca$col$coord, 
  musics = rownames(res.ca$col$coord))

pc <- ggplot() +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_label(aes(Dim.1, Dim.2, color = I(colorCodes), label = colorNames),
             dat.row, size = 2, fontface = 2) +
  geom_point(aes(Dim.1, Dim.2), dat.col, shape = "♪", size = 4) +
  geom_text_repel(aes(Dim.1, Dim.2, label = musics), dat.col, fontface = 3) +
  theme_bw() +
  labs(x = "Dim. 1 (38.6%)",
       y = "Dim. 2 (25.9%)",
       title = "CA factor map")

pc
```


## Interactive CA

```{r interactive}

# dat.col$onclick <- sprintf('var audio= new Audio("https://lasonotheque.org/UPLOAD/mp3/187%i.mp3"); audio.play();', 1:9)

dat.col$onclick <- 'var audio= new Audio("music/lowF.mp3"); audio.play();'
dat.col$onclick <- 'var audio= new Audio("https://lasonotheque.org/UPLOAD/mp3/1871.mp3"); audio.play();'
dat.col$onclick <- sprintf('var audio= new Audio("%s/1871.mp3"); audio.play();', getwd())

dat.col$onclick <- "var audio= new Audio(\"/Users/vguillem/Library/CloudStorage/Box-Box/SPAFAC/fourbi/sCA_Saporta/1871.mp3\"); audio.play();"

dat.col$onclick <- 'var audio= new Audio("https://localhost:4321/1871.mp3"); audio.play();'

dat.col$onclick <- 'var audio= new Audio("<filepath>/1871.mp3"); audio.play();'

pc.int <- ggplot() +
  geom_hline(yintercept = 0, color = "grey") +
  geom_vline(xintercept = 0, color = "grey") +
  geom_label(aes(Dim.1, Dim.2, color = I(colorCodes), label = colorNames),
             dat.row, size = 2, fontface = 2) +
  geom_point_interactive(aes(Dim.1, Dim.2, onclick = onclick), dat.col, shape = "♪", size = 4) +
  geom_text_repel(aes(Dim.1, Dim.2, label = musics), dat.col, fontface = 3) +
  theme_bw() +
  labs(x = "Dim. 1 (38.6%)",
       y = "Dim. 2 (25.9%)",
       title = "CA factor map")


girobj <- girafe(
  ggobj = pc.int)

girobj

```

